
insert into frases(id, frase, personaje, titulo, poster) values (1, 'Oh, sí... El pasado puede doler, pero tal como yo lo veo puedes huir de él o aprender', 'Rafiki', 'El rey León', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiRLse16Bba4ZjyrOwoa4hq-qMOmbwwFeE0wFpwGkssm88My_s0U3k6YG_QA43tiOH8Cv8AX7JbcX2uki3gxf6_6d3Kjr7B_plvd87fLWRhjLhSE8ltt_5xwDC3sE6AmdcwfRkqcBnXvNo/s1600/32+-+El+Rey+Le%C3%B3n.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (2, '¿Sabes por qué los lobos cazan en manada? Porque sus presas favoritas son demasiado grandes para ser derribadas por uno solo.', 'Peter Hale.', 'Teen Wolf', 'https://pics.filmaffinity.com/Teen_Wolf_Serie_de_TV-614017053-large.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (3, 'Sí, se llama desamor. Hay como dos mil millones de canciones escritas acerca de ello', 'Stiles Stilinski.', 'Teen Wolf', 'https://pics.filmaffinity.com/Teen_Wolf_Serie_de_TV-614017053-large.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (4, 'Somos solo personas. Nos equivocamos, perdemos el rumbo. Incluso los mejores tienen sus malos días. Aún así seguimos adelante', 'Meredith Grey', 'Grey''s Anatomy', 'https://m.media-amazon.com/images/M/MV5BODA2Mjk0N2MtNGY0Mi00ZWFjLTkxODEtZDFjNDg4ZDliMGVmXkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_SX300.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (5, 'La vida es como una caja de bombones, nunca sabes lo que te va a tocar.', 'Forrest Gump', 'Forrest Gump', 'https://m.media-amazon.com/images/S/pv-target-images/f9ddd832d1b566f5b8dd29a4dbc76b7531c420c8c8d9fdfe94eca128bda8e2b1.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (6, 'No quiero sobrevivir, quiero vivir.', 'Solomon Northup', '12 años de esclavitud.', 'https://m.media-amazon.com/images/I/817eOUfdeXL._AC_UF894,1000_QL80_.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (7, 'No importa cuánto golpees, sino cuánto puedas aguantar y seguir adelante. Cuánto puedes soportar y seguir adelante. Así es como se gana.', 'Rocky Balboa', 'Rocky', 'https://m.media-amazon.com/images/M/MV5BNWIyNmQyNjctYmVmMS00MGI4LWIxMmUtNjA0ODYzOTA0Yjk0L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (8, '¡Que la fuerza te acompañe!', 'Obi Wan Kenobi', 'Star Wars', 'https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (9, 'Me salvaste de todas las formas que alguien puede ser salvado.', 'Rose Dawson', 'Titanic', 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (10, 'Me diste una eternidad dentro de nuestros días contados, y estoy muy agradecida por eso.', 'Hazel', 'Bajo la misma estrella', 'https://m.media-amazon.com/images/M/MV5BNTVkMTFiZWItOTFkOC00YTc3LWFhYzQtZTg3NzAxZjJlNTAyXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (11, 'Lo único predecible de la vida es su impredecibilidad.', 'Remy', 'Ratatouille', 'https://lumiere-a.akamaihd.net/v1/images/p_ratatouille_19736_0814231f.jpeg');
insert into frases(id, frase, personaje, titulo, poster) values (12, 'La flor que florece en la adversidad es la más rara y hermosa de todas.', 'El Emperador', 'Mulan', 'https://m.media-amazon.com/images/I/81etxQuCMnL._AC_UF894,1000_QL80_.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (13, 'El amor es poner las necesidades de alguien más antes que las tuyas', 'Olaf', 'Frozen', 'https://i.pinimg.com/236x/43/ca/f0/43caf0cdc44989104ea68ebc94e84209.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (14, 'Eres más valiente de lo que crees, más fuerte de lo que pareces, y más inteligente de lo que piensas', 'Christopher Robin', 'Winnie the Pooh.', 'https://play-lh.googleusercontent.com/2_KJXaxVRp_rnE4_qWR_O0OPXlgp3dp-aEZCEtQLugp_QQEng7dsq3w9RqADoEBUrhBn');
insert into frases(id, frase, personaje, titulo, poster) values (15, 'A veces, cuando te estás perdiendo, puedes encontrar una mejor versión de ti mismo.', 'Sabrina Spellman', 'Chilling Adventures of Sabrina.', 'https://resizing.flixster.com/mp662_hMit1v-dVNJsYDvTkxADw=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjgxMjU4My53ZWJw');
insert into frases(id, frase, personaje, titulo, poster) values (16, 'Si quieres hacer del mundo un lugar mejor, mira en tu interior y haz un cambio', 'Lucifer Morningstar.', 'Lucifer', 'https://m.media-amazon.com/images/I/81LayHiQyoL._AC_UF894,1000_QL80_.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (17, 'Los muertos no sufren, solo los vivos.', 'Victor Van Dort.', 'El cadáver de la novia', 'https://es.web.img3.acsta.net/medias/nmedia/18/89/76/03/20065463.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (18, 'El que se da por vencido pierde más que una carrera', 'Doc Hudson.', 'Cars', 'https://cdn.shopify.com/s/files/1/0310/7487/7577/products/00722-Cars-_Blackstone__Rounded_13457a25-19b0-4840-9fa0-bb5cddd25a3c.webp?v=1673448458');
insert into frases(id, frase, personaje, titulo, poster) values (19, '¡Estás loco, chiflado, demente! Pero te diré un secreto: las mejores personas lo están.', 'El Sombrerero Loco.', 'Alicia en el País de las Maravillas',  'https://www.ecartelera.com/carteles/3300/3332/001_p.jpg');
insert into frases(id, frase, personaje, titulo, poster) values (20, 'Yo estoy loco. Tú estás loca. ¿Cómo sabes que estoy loco? Tienes que estarlo para venir aquí.', 'Gato de Cheshire.', 'Alicia en el País de las Maravillas',  'https://pics.filmaffinity.com/Alicia_en_el_paais_de_las_maravillas-108542060-large.jpg');

SELECT * FROM frases

DELETE FROM frases
